accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
    path('password/', views.password, name="password"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    # path('', posts_views.index, name="root"),
    path('', posts_views.list, name="root"),  # root 페이지 설정
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name="people")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.list, name="list"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/like/', views.like, name="like"),
    path('<int:post_id>/create/comment/', views.create_comment, name="create_comment"),
    path('<int:post_id>/delete/comment/<int:comment_id>/', views.delete_comment, name="delete_comment"),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    nickname = models.CharField(max_length=40, blank=True)
    image = models.ImageField(blank=True, upload_to="")

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

posts/models.py
from django.db import models

# from django.contrib.auth.models import User  # 예전 방식
from django.conf import settings



# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True, upload_to="")
    
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
    def __str__(self):
        return self.content


class Comment(models.Model):
    content = models.CharField(max_length=300)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields  # 생략해도 무방




class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['description', 'nickname', 'image']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate, get_user_model, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from .forms import LoginForm, CustomUserChangeForm, ProfileForm, CustomUserCreationForm
from .models import Profile, User

# Create your views here.
def login(request):
    if request.method == "POST": # POST : 실제 로그인 (세션에 유저 정보 추가)
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            # next 정의돼 있으면, 해당 URL로 redirect // 정의돼있지 않으면, posts:list로 redirect
            return redirect(request.GET.get('next') or 'posts:list')
    
    else: # GET : 로그인 정보 입력
        form = AuthenticationForm()
    return render(request, 'accounts/login2.html', {
        'form': form,
    })
    
    #######################################################################
    
    # login_form = LoginForm(request.POST)
    # if login_form.is_valid():
    #     username = login_form.cleaned_data['username']
    #     password = login_form.cleaned_data['password']
        
    #     user = authenticate(
    #         username=username,
    #         password=password
    #     )
        
    #     if user:
    #         auth_login(request, user)
    #         return redirect('posts:list')
    #     login_form.add_error(None, 'Incorrect ID or password')
    # else:
    #     login_form = LoginForm()
    # return render(request, 'accounts/login.html', {
    #     'login_form': login_form,
    # })

 ######################################################################
 
 
 
def logout(request):
    auth_logout(request)
    return redirect('posts:list')
    
    

def signup(request):
    if request.method == "POST": # POST - 유저 등록
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect('posts:list')
        else:
            return redirect('accounts:signup')
    else: # GET - 유저 정보 입력 받음
        form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })
    

def people(request, username):
    # 사용자에 대한 정보
    people = get_object_or_404(get_user_model(), username=username)
    # 유저 객체 표현 방법:
    # 1. settings.AUTH_USER_Model  (from django.conf)
    # 2. get_user_model()  ###
    
    return render(request, 'accounts/people.html' ,{
        'people': people,
    })
    
    
# 회원 정보 변경 (편집 & 반영)
def update(request):
    if request.method == "POST":  # 반영
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        # profile_form = ProfileForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_change_form.is_valid() and profile_form.is_valid():
            user = user_change_form.save()
            profile_form.save()
            return redirect('people', user.username)
    else: # "GET"  # 편집
        user_change_form = CustomUserChangeForm(instance=request.user)
        
        ##### ISSUE:  instance 를 넣어줄 정보가 있는 유저가 있고, 없는 유저도 있다.
        ### Solution 1
        # if Profile.objects.get(user=request.user):
        #     profile = Profile.objects.get(user=request.user)
        # else:
        #     profile = Profile.objects.create(user=request.user)
            
        ### Solution 2    
        profile, created = Profile.objects.get_or_create(user=request.user) 
              # get_or_create : Returns a tuple of (object, created), where object is the retrieved or created object and created is a boolean specifying whether a new object was created.
        profile_form = ProfileForm(instance=profile)
        
        
        return render(request, 'accounts/update.html', {
            'user_change_form': user_change_form,
            'profile_form': profile_form,
        })
    

# 회원 탈퇴
def delete(request):
    if request.method == "POST":  # 탈퇴 로직
        request.user.delete()
        return redirect('posts:list')
        # return redirect('accounts:signup')
    return render(request, 'accounts/delete.html')

# 비밀번호 변경
def password(request):
    if request.method == "POST":
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            return redirect('people', request.user.username)
    else: #"GET"
        password_change_form = PasswordChangeForm(request.user)
        return render(request, 'accounts/password.html', {
            'password_change_form': password_change_form,
        })

def follow(request, user_id):
    person = get_object_or_404(get_user_model(), pk=user_id)
    
    # 만약 현재 유저가 해당 유저를 이미 팔로우하고 있었으면, 언팔로우 (remove)
    if request.user in person.followers.all():
        person.followers.remove(request.user)
    
    # 반대로, 팔로우를 안 하고 있었다면 팔로우 한다.   (add)
    else:
        person.followers.add(request.user)
    
    return redirect('people', person.username)

accounts/templates/accounts/delete.html
{% extends 'base.html' %}


{% block body %}

<form method="POST">
    {% csrf_token %}
    <h3>정말로 탈퇴하시겠습니까?</h3>
    <button type="submit" class="btn btn-danger">탈퇴</button>
</form>

    
{% endblock%}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}
{% block body %}
<div class="login">
	<form action="" method="post">
		{% csrf_token %}
		{% for field in login_form %}
			<div class="form-group">
				{{ field.label_tag }}
				{{ field }}
				{% if field.errors %}
					{% for error in field.errors %}
					<span class="help-block">{{ error }}</span>
					{% endfor %}
				{% endif %}
			</div>
		{% endfor %}

		{% if login_form.non_field_errors %}
			{% for error in login_form.non_field_errors %}
			<p class="text-danger"><b>{{ error }}</b></p>
			{% endfor %}
		{% endif %}
		<button class="btn btn-primary btn-block">로그인</button>
	</form>
</div>
{% endblock %}

accounts/templates/accounts/login2.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1>Login</h1>

{% comment %}
<!-- <form method="POST" action="{% url 'accounts:login' next=request.GET.get('next') %}"> -->
<!-- 위처럼 action을 넣게 되면 next action이 잘 넘어가지 않게 된다. 따라서 next를 명시적으로 지정해주어야 한다. -->
<!-- 그러나 Django convention으로는 이 경우에 아예 action을 쓰지 않는 게 더 좋다. (동일 action으로 GET/POST 구분하는 상황에서) -->
{% endcomment %}


<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button class="btn btn-primary" type="submit">Login</button>
</form>
{% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

<h1>비밀번호 변경</h1>

<form method="POST">
  {% csrf_token %}
  {% bootstrap_form password_change_form %}
  <button class="btn btn-primary" type="submit">Change</button>
</form>

{% endblock%}

accounts/templates/accounts/people.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-4">
      {% if people.profile.image %}
        <img src="{{ people.profile.image.url }}" class="profile_image">
      {% else %}
        <img src="https://ultimatemember.com/wp-content/uploads/bb-plugin/cache/instagram-circle.png" class="card-img-top">
      {% endif %}
    </div>
    <div class="col-8">
      <h3 class="mt-5">{{ people.username }}
        {% if request.user != people %}
          {% if request.user in people.followers.all %}
            <a href="{% url 'accounts:follow' people.id %}" class="btn btn-outline-primary">Unfollow</a>
          {% else %}
            <a href="{% url 'accounts:follow' people.id %}" class="btn btn-primary text-white">Follow</a>
          {% endif %}
        {% else %}
          <a class="btn btn-info" href="{% url 'accounts:update' %}">정보수정</a>
          <a class="btn btn-warning" href="{% url 'accounts:password' %}">비번변경</a>
          <a class="btn btn-danger" href="{% url 'accounts:delete' %}">탈퇴</a>
        {% endif %}
      </h3>
      <div class="card-text">{{ people.last_name }}{{people.first_name}}</div>
      <div class="card-text">{{ people.profile.nickname }}</div>
      <div class="card-text">{{ people.profile.description }}</div>
    </div>
    
  </div>
  
  
  <div class="row mt-3">
    {% for post in people.post_set.all %}
      <div class="col-4">
        {% if post.image %}
          <img src="{{ post.image.url }}" class="img-fluid"></img>
        {% else %}
          <img src="https://picsum.photos/300/300/?random" class="img-fluid"></img>
        {% endif %}
      </div>
    {% endfor %}
  </div>
</div>
{% endblock%}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1>Sign Up</h1>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button class="btn btn-primary" type="submit">Sign Up</button>
</form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

<h1>회원정보변경</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form user_change_form %}
  {% bootstrap_form profile_form %}
  <button class="btn btn-primary" type="submit">Change</button>
</form>
    
{% endblock%}