accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
    path('password/', views.password, name="password"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    # path('', posts_views.index, name="root"),
    path('', posts_views.list, name="root"),  # root 페이지 설정
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name="people")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.list, name="list"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/like/', views.like, name="like"),
    path('<int:post_id>/create/comment/', views.create_comment, name="create_comment"),
    path('<int:post_id>/delete/comment/<int:comment_id>/', views.delete_comment, name="delete_comment"),
]

posts/models.py
from django.db import models

# from django.contrib.auth.models import User  # 예전 방식
from django.conf import settings



# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True, upload_to="")
    
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
    def __str__(self):
        return self.content


class Comment(models.Model):
    content = models.CharField(max_length=300)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Comment

# Post라는 모델을 조작할 수 있는 PostModelForm 정의
class PostForm(forms.ModelForm):
    # 1. 어떤 input field를 가지는지
    content = forms.CharField(label="content", widget=forms.Textarea(attrs={
        'placeholder': '오늘은 무엇을 하셨나요?'
    }))
    
    # 2. 해당 input field의 속성을 추가 & 어떤 모델을 조작할지
    class Meta:
        model = Post
        # fields = "__all__"
        fields = ['content', 'image']
        


class CommentForm(forms.ModelForm):
    content = forms.CharField(label="댓글", widget=forms.TextInput(attrs={
        'placeholder': 'Comment'
        
    }))
    
    class Meta:
        model = Comment
        fields = ['content']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm
from .models import Post, Comment
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.
def index(request):
    return redirect('posts:list')

@login_required
def create(request):
    if request.method == "POST":
        # 작성된 포스트(게시글)를 DB에 적용
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:list')
    else: # GET 방식
        # 포스팅을 작성하는 form을 보여줌.
        form = PostForm()
        return render(request, 'posts/create.html', {
            'form': form
        })


@login_required
def list(request):
    ##### 모든 포스트를 보여준다
    # posts = Post.objects.all()
    
    ##### 내가 팔로우한 사람들의 포스트 + 내가 작성한 포스트만 보여줌
    if request.user.is_authenticated:
        posts = Post.objects.filter(Q(user_id__in=request.user.followings.all()) | Q(user=request.user)).order_by('-id')
        
        # my_filter = Q(user=request.user)
        # for user in request.user.followers.all():
        #     my_filter = my_filter | Q(user=user)
        # posts = Post.objects.filter(my_filter).order_by('-id')
    
    else:
        posts = None
    
    
    comment_form = CommentForm()
    return render(request, 'posts/list.html', {
        'posts': posts,
        'comment_form': comment_form,
    })

@login_required
@require_POST
def create_comment(request, post_id):
    comment_form = CommentForm(request.POST)
    post = get_object_or_404(Post, pk=post_id)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.user = request.user
        comment.save()
        return redirect('posts:list')

def delete_comment(request, post_id, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    return redirect('posts:list')

    
#@require_POST   # POST method만 accept하고 싶을 때 => if request.method == "POST": 를 쓰는 것과 동일
def delete(request, id):
    post = Post.objects.get(pk=id)
    if post.user != request.user:
        return redirect('posts:list')
    post.delete()
    return redirect('posts:list')

def update(request, id):
    # post = Post.objects.get(pk=id)
    post = get_object_or_404(Post, pk=id)
    if request.method == "GET":
        form = PostForm(instance=post)
        return render(request, 'posts/update.html', {
            'form': form,
        })
    else: # "POST"
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
    
@login_required
def like(request, id):
    # 1. like를 추가할 포스트를 가져옴
    post = get_object_or_404(Post, pk=id)
    
    # 2. 만약 유저가 해당 post를 이미 like했다면 like를 제거하고,
    #    like가 돼 있는 상태가 아니라면 like를 추가한다.
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    
    return redirect('posts:list')

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block body %}
<form method="POST" enctype="multipart/form-data">
  <!--Model Form 사용할 것.-->
  <!--{{ form }}-->
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">Upload</button>
</form>

{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <div class="row justify-content-center my-5">
    {% for post in posts %}
      <div class="card" style="width: 25rem;">
        <div class="card-header">
          <span><a href="{% url 'people' post.user.username %}">{{ post.user }}</a></span>
        </div>
        {% if post.image %}
          <img src="{{ post.image.url }}" class="card-img-top" alt="...">
        {% else %}
          <img src="https://picsum.photos/300/300/?random" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body">
          <p class="card-text">{{ post.content }}</p>
          
          <!-- 작성자만 수정/삭제 가능하도록 만듦 -->
          {% if post.user == request.user %}
            <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">Delete</a>
            <a href="{% url 'posts:update' post.id %}" class="btn btn-warning">Edit</a>
          {% endif %}
        </div>
        <!-- Like Button -->
        <div class="card-body">
          <a href="{% url 'posts:like' post.id %}">
            <!--유저가 좋아요 했다면 colored heart; otherwise empty heart-->
            {% if user in post.like_users.all %}
            <i class="fas fa-heart"></i>
            {% else %}
            <i class="far fa-heart"></i>
            {% endif %}
          </a>
          <p class="card-text">
            {{ post.like_users.count }} 명이 좋아합니다.
          </p>
        </div>
        
        <!-- Comment 댓글 -->
        <div class="card-body">
          <!-- Comment에 대한 ModelForm -->
          {% if request.user.is_authenticated %}
          <form method="POST" action="{% url 'posts:create_comment' post.id %}">
            <!-- bootstrap_form -->
            {% bootstrap_form comment_form %}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Comment</button>
          </form>
          <hr>
          {% else %}
          <a href="{% url 'accounts:login' %}">Login</a> to write comments
          <hr>
          {% endif %}
          <!-- 해당 글에 작성된 댓글들을 모두 출력하기 -->
          {% for comment in post.comment_set.all %}
            <div class="card-text"><strong>[{{comment.user.username}}]</strong> {{comment.content}}
            {% if request.user == post.user or request.user == comment.user %}
            <a href="{% url 'posts:delete_comment' post.id comment.id %}">[X]</a>
            {% endif %}
            </div>
          {% empty %}
            <div class="card-text">
              첫 댓글을 달아주세요
            </div>
          {% endfor %}
          
        </div>
        
      </div>
    {% endfor %}
  </div>



{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<form method="POST">
  <!--Model Form 사용할 것.-->
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">Upload</button>
</form>
{% endblock %}